version: "3.8"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/app
        depends_on:
            - db
            - app
        restart: always
        networks:
            - network-name

    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./:/var/www/app
        networks:
              - network-name

    db:
        image: mariadb
        container_name: db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD_MYSQL}
        ports:
            - '3311:3306'
        volumes:
            - ./docker/mariadb/db_data:/var/lib/mysql
        networks:
            - network-name
networks:
    network-name:
        driver: bridge
volumes:
    db_data:
